name: Build vos-dev ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y live-build

    - name: Run build script
      run: bash scripts/build.sh

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3
      with:
        name: vos-dev-iso
        path: vos-dev-live/live-image-amd64.hybrid.iso
